import type {Metadata} from "next";
import {ThemeContextProvider} from "./theme/ThemeContext";
import "./globals.css";
import ClientWrapper from "./components/client-wrapper";

export const metadata: Metadata = {
  title: "Place des arcades",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <ClientWrapper>{children}</ClientWrapper>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
